### ISSUE TITLE
Mantener la sesion del usuario iniciada

### ISSUE THREAD

**Issue by earias08** [manu071202/trabajoJsEntrega#8]
Al usar el login, debo poder navegar entre las diferentes paginas sin perder la sesion. Por ej cuando nos logueamos como administrador y vamos a la pagina de inicio no podemos volver a la pagina de administrador

![image](https://user-images.githubusercontent.com/18445151/191385705-fdb97140-cc86-482d-9c37-79aabc126667.png)

**Comment by nicofara27** [comment]
Agregamos un switch para que los botones de administrador y cerrar sesion permanezcan activos de esta manera podremos identificarnos desde cualquier pagina y si somos un usuario admin podriamos volver a la pagina del administrador.
