### ISSUE TITLE
Agregar una opcion de cerrar sesion

### ISSUE THREAD

**Issue by earias08** [manu071202/trabajoJsEntrega#9]
Una vez iniciada la sesion, agregar un boton en el navbar que permita cerrar dicha sesion.

**Comment by nicoelias997** [comment]
Agregamos logica para cuando un usuario se identifique, el btn identificarse no se vea, y se vea el btn cerrar sesion. Que a su vez, definimos dos usuarios de prueba, con los cuales el usuario 1(grupo@gmail.com, rolling); si ingresamos con este, se mostrara el btn administrador, en cambio si ingresamos con el usuario 2(martin@gmail.com, martin) unicamente podremos ver el inicio!
